KOGITO-3622 - Add grafana to kogito-infra
kiegroup/kogito-cloud-operator pull request #617
Opened 2020-10-19 13:26 UTC by r00ta

Jira: https://issues.redhat.com/browse/KOGITO-3622

Scenario: Trusty Monitoring
As you can see in the following schema 
![overall (1)1](https://user-images.githubusercontent.com/18282531/96453775-3eaeeb80-121b-11eb-9025-387d96d4a5f2.png)
there are two external resources: prometheus and grafana. The prometheus instance is already managed by the operator, but the grafana resources not. 

The workflow is the following: 
1) A kogito runtime application with the monitoring addon is compiled and a docker image is built. That application will expose the name of the dashboards under the path `/monitoring/dashboards/list.json`. `list.json` contains the name of the dashboards that can be downloaded at `/monitoring/dashboards/xxx.json`. 
2) In case the user uses the grafana `kogito-infra` resource, he has to create it. Otherwise he has to install and deploy a grafana operator resource. 
3) When the kogito runtime application is deployed with the operator (a special flag `enableGrafanaDashboards` must be set) ,then the operator will fetch the dashboards and will create grafana dashboards out of them -> the related jira ticket is the following:   https://issues.redhat.com/browse/KOGITO-3624

Please, note that the final feature is composed by the following PR/ticket and the ticket https://issues.redhat.com/browse/KOGITO-3624 that still has to be implemented by me. 

Many thanks for submiting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors' guide](https://github.com/kiegroup/kogito-cloud-operator/blob/master/README.md#contributing-to-the-kogito-operator)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Your feature/bug fix has a unit test that verifies it
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster

2020-10-19 14:03 UTC, spolti commented on pkg/controller/kogitoinfra/grafana/resource.go
> +func createNewGrafanaInstance(cli *client.Client, name string, namespace string, instance *v1alpha1.KogitoInfra, scheme *runtime.Scheme) (*grafana.Grafana, error) {
will we going continue to provision infra for user?

2020-10-19 14:07 UTC, spolti requested changes
just a little thing.

@ricardozanini haven't we decided to no create infra anymore or will continue doing it and later let this only for dev mode?

2020-10-19 14:07 UTC, spolti commented on pkg/controller/kogitoinfra/kogitoinfra_service.go
> +// isGrafanaResource check if provided KogitoInfra instance is for Keycloak resource
grafana?

2020-10-19 15:13 UTC, ricardozanini requested changes
Hi @r00ta! 

Thanks for your PR, but this is not the strategy we are aiming for 1.0

`KogitoInfra` is meant to **bind** the Kogito services with third party infra, not creating the infra itself. We just kept Kafka/Infinispan/Keycloak for now for backward compatibility.

For Kafka: We create KafkaTopics on already created Kafka instance.
For Infinispan: We fetch Infinispan server details and inject it into the service, so it could connect to it
For Knative Eventing: We bind a given broker with a Kogito service via SinkBindings and Triggers.
For Prometheus: We fetch for the `metrics` endpoint and create `ServiceMonitors` to bind then together, no `KogitoInfra` needed.

For Graphana: Users should create their own Graphana instance and the operator would fetch for the `/dashboards` endpoint, if it's in there, we create [GraphanaDashboards](https://github.com/integr8ly/grafana-operator/blob/master/documentation/dashboards.md) to be discovered by the Graphana Operator. We **won't create** Graphana instances whatsoever.

I'd say that we won't merge this PR since it's not the strategy we are aiming.

2020-10-20 11:45 UTC, r00ta commented
Hi @ricardozanini , thanks for the clarification. np, I'll implement what you just suggested. I'll close this

2020-10-20 11:45 UTC, closed without merging

2020-10-20 13:07 UTC, ricardozanini commented
> Hi @ricardozanini , thanks for the clarification. np, I'll implement what you just suggested. I'll close this

Take a look at #602 it's pretty similar: we fetch for topics and create Knative resources.