[KOGITO-3715] Kogito Operator installer bundle
kiegroup/kogito-cloud-operator pull request #635
Opened 2020-10-28 21:16 UTC by ricardozanini

Signed-off-by: Ricardo Zanini <zanini@redhat.com>

Now the community would deploy the desired Operator version easily without OLM:

```
kubectl apply -f http://github.com/.../v1.0.0/kogito-operator.yaml -n mynamespace
```

@ibek this is my gift for you

@radtriste do you mind taking a look/testing the Jenkins side? I believe I did it right... but who knows.

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors' guide](https://github.com/kiegroup/kogito-cloud-operator/blob/master/README.md#contributing-to-the-kogito-operator)
- [ ] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster

2020-10-28 21:22 UTC, ricardozanini commented
Tomorrow I update the `install.sh` file.

2020-10-28 22:32 UTC, ibek commented
@ricardozanini :) thanks a lot, looking forward to trying it out on K8s

2020-10-29 12:25 UTC, ricardozanini commented
LINT error can be ignored for now since this is the first PR to introduce the file.

2020-10-29 12:26 UTC, Kaitou786 approved these changes

2020-10-29 12:44 UTC, radtriste requested changes
Can you also add a note in README ?

2020-10-29 12:44 UTC, radtriste commented on hack/bump-version.sh
> +sed -i "s/$old_version/$new_version/g" cmd/kogito/version/version.go README.md version/version.go deploy/operator.yaml ${OLM_DIR}/kogito-operator.package.yaml ${OLM_DIR}/custom-subscription-example.y
not sure this is needed as you anyway remove the `kogito-operator.yaml` file in the `make vet` command

2020-10-29 14:04 UTC, radtriste approved these changes

2020-10-29 14:17 UTC, spolti requested changes
minor thing;

2020-10-29 14:17 UTC, spolti commented on README.md
> +Replace the values above to match your context. The version information you can grab from the [releases page]().
missing the releases link.

2020-10-29 16:18 UTC, ricardozanini commented on README.md
> +Replace the values above to match your context. The version information you can grab from the [releases page]().
Dammit!

2020-10-29 16:18 UTC, ricardozanini commented on README.md
> +Replace the values above to match your context. The version information you can grab from the [releases page]().
```suggestion
Replace the values above to match your context. The version information you can grab from the [releases page](https://github.com/kiegroup/kogito-cloud-operator/releases).
```

2020-10-29 16:51 UTC, spolti commented
lint fail on kogito-operator.yaml.

2020-10-29 17:33 UTC, ricardozanini commented
> lint fail on kogito-operator.yaml.

> LINT error can be ignored for now since this is the first PR to introduce the file.

hehehe

2020-10-29 17:33 UTC, merged