Update install_explainability.feature
kiegroup/kogito-cloud-operator pull request #688
Opened 2020-12-04 10:41 UTC by r00ta

This fixes

Error is:
Error in scenario 'Explainability retrieves explainability requests events': Outcome Is Enought? for execution LoanEligibility was not found
on both
https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/kogito/job/kogito-operator-deploy/354/artifact/test/logs/full/error%20-%20Explainability%20retrieves%20explainability%20requests%20events%20-%20jenkins-cucumber-5821/test-run.log
https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/kogito/job/kogito-operator-deploy/354/artifact/test/logs/full/error%20-%20Explainability%20retrieves%20explainability%20requests%20events%20using%20external%20Kafka%20-%20jenkins-cucumber-a7ed/test-run.log

Many thanks for submitting your 

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [ ] You have read the [contributors' guide](https://github.com/kiegroup/kogito-cloud-operator/blob/master/README.md#contributing-to-the-kogito-operator)
- [ ] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [ ] Pull Request contains a link to the JIRA issue
- [ ] Pull Request contains a description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster
- [ ] You've added a [RELEASE_NOTES.md](RELEASE_NOTES.md) entry regarding this change

2020-12-04 11:40 UTC, sutaakar commented
@r00ta Can you please use/create a JIRA for this PR and adjust the PR according to requirements above?

2020-12-04 12:53 UTC, r00ta commented
@sutaakar done

2020-12-04 16:18 UTC, radtriste requested changes

2020-12-04 16:18 UTC, radtriste commented on test/features/install_explainability.feature
> +      | Is Enough?  |
shoudn't you update that one also in the next scenario ?

2020-12-05 10:31 UTC, r00ta commented
/Jenkins test this

2020-12-05 10:32 UTC, r00ta commented
/jenkins retest this please

2020-12-05 11:31 UTC, r00ta commented
@radtriste can we move forward with this?

2020-12-07 07:30 UTC, radtriste approved these changes

2020-12-07 07:31 UTC, merged