[KOGITO-4110-cherrypick] - Single namespaced operator reacts on CRs created in d…
kiegroup/kogito-cloud-operator pull request #713
Opened 2021-01-08 14:43 UTC by Kaitou786

…ifferent namespaces

See: https://issues.redhat.com/browse/KOGITO-4110

Signed-off-by: Tarun Khandelwal <tarkhand@redhat.com>

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [ ] You have read the [contributors' guide](https://github.com/kiegroup/kogito-cloud-operator/blob/master/README.md#contributing-to-the-kogito-operator)
- [ ] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [ ] Pull Request contains a link to the JIRA issue
- [ ] Pull Request contains a description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster
- [ ] You've added a [RELEASE_NOTES.md](RELEASE_NOTES.md) entry regarding this change

2021-01-08 15:26 UTC, spolti commented on cmd/manager/main.go
> +	if ns == "" {
I think len(ns) > 0 is better to check empty vars.

2021-01-08 15:26 UTC, spolti requested changes

2021-01-08 15:26 UTC, spolti commented on cmd/manager/main.go
> +	if ns == "" {
just a idea.

2021-01-08 15:28 UTC, spolti requested changes

2021-01-08 15:28 UTC, spolti commented on cmd/manager/main.go
> +	if ns == "" {
I think that

```
len(ns) > 0
```

is better to verify empty vars.

2021-01-08 17:38 UTC, radtriste approved these changes
Tested:

- Operator as cluster-wide => OK
- Operator as namespace-wide and kogito resource in same namespace => OK
- Operator as namespace-wide and kogito resource in a different namespace => OK, nothing created

2021-01-10 16:16 UTC, Kaitou786 commented
/jenkins prior test

2021-01-10 16:19 UTC, Kaitou786 commented
/jenkins prior test

2021-01-10 16:24 UTC, Kaitou786 commented
/jenkins prior test

2021-01-10 16:34 UTC, Kaitou786 commented
/jenkins prior test

2021-01-10 16:41 UTC, Kaitou786 commented
/jenkins prior test

2021-01-10 16:56 UTC, Kaitou786 commented
/jenkins prior test

2021-01-10 17:08 UTC, Kaitou786 commented
/jenkins test

2021-01-11 08:44 UTC, radtriste commented
/jenkins test

2021-01-11 08:49 UTC, Kaitou786 commented
/jenkins test

2021-01-11 09:36 UTC, radtriste commented
tests ok. @spolti please review and merge so it can be included in 1.1.x

2021-01-11 15:01 UTC, ricardozanini approved these changes

2021-01-11 15:37 UTC, spolti approved these changes

2021-01-11 15:38 UTC, merged