[KOGITO-4133] - API rule violation when running openapi-gen
kiegroup/kogito-cloud-operator pull request #718
Opened 2021-01-13 09:50 UTC by Kaitou786

The internal and the exposed name should be same, changing the internal name to `Volumes` since it is a list so makes more sense to me 

See: https://issues.redhat.com/browse/KOGITO-4133

Signed-off-by: Tarun Khandelwal <tarkhand@redhat.com>

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [ ] You have read the [contributors' guide](https://github.com/kiegroup/kogito-cloud-operator/blob/master/README.md#contributing-to-the-kogito-operator)
- [ ] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [ ] Pull Request contains a link to the JIRA issue
- [ ] Pull Request contains a description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster
- [ ] You've added a [RELEASE_NOTES.md](RELEASE_NOTES.md) entry regarding this change

2021-01-13 09:53 UTC, Kaitou786 commented
/jenkins test

2021-01-13 10:32 UTC, Kaitou786 commented
/jenkins test

2021-01-13 12:45 UTC, ricardozanini requested changes
`Volume` as `Env` (singular) is what we are using to follow with k8s conventions. The PodSpecTemplate keep them singular, I think we have to keep the same.

EDIT: actually on [`PodSpecTemplate`](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#podspec-v1-core), the attribute is `volumes` (plural). Well, I guess they also missed the coherence point here. :laughing:

2021-01-13 12:51 UTC, ricardozanini approved these changes

2021-01-14 20:34 UTC, spolti approved these changes

2021-01-15 20:17 UTC, merged