[KOGITO-4546] - Create make olm-manifests target responsible for crea…
kiegroup/kogito-cloud-operator pull request #773
Opened 2021-02-25 10:48 UTC by Kaitou786

…ting manifests in same pattern accepted by the OLM

See: https://issues.redhat.com/browse/KOGITO-4546

Signed-off-by: Tarun Khandelwal <tarkhand@redhat.com>

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [ ] You have read the [contributors' guide](https://github.com/kiegroup/kogito-cloud-operator/blob/master/README.md#contributing-to-the-kogito-operator)
- [ ] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [ ] Pull Request contains a link to the JIRA issue
- [ ] Pull Request contains a description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster
- [ ] You've added a [RELEASE_NOTES.md](RELEASE_NOTES.md) entry regarding this change

2021-02-25 13:02 UTC, ricardozanini requested changes
Do you mind writing a session in the CONTRIBUTING or README file explaining when we would need this manifest? I assume we would need it to send a PR to the Community Operators project.

2021-02-25 13:17 UTC, ricardozanini commented on README.md
> +Before raising the PR, make sure the `replaces` field in the CSV is correct
```suggestion
Before raising the PR, make sure the `replaces` field in the CSV is correct.
```

2021-02-25 13:17 UTC, ricardozanini approved these changes

2021-02-25 13:19 UTC, ricardozanini approved these changes

2021-02-25 13:23 UTC, sutaakar approved these changes

2021-02-25 13:27 UTC, Kaitou786 commented
Thinking about it, do you guys think we should cherry-pick to the 1.3.x branch as well?
Would be easier when doing the release

2021-02-25 14:58 UTC, Kaitou786 commented
Removed the metrics files as they are causing problems when upgrading the operator @ricardozanini many thanks for the suggestion! <3

2021-02-25 15:11 UTC, sutaakar approved these changes

2021-03-01 12:34 UTC, ricardozanini approved these changes

2021-03-01 12:58 UTC, spolti approved these changes

2021-03-01 13:00 UTC, merged